---
- name: Playbook to use OpenSCAP
  hosts: 127.0.0.1
  connection: local
  vars:
    openscap_version: 1.2.14
    scap_security_guide_version: 0.1.31
  tasks:
  - name: Update repository cache and install build-essential for building OpenSCAP
    apt:
      name: build-essential
      update-cache: yes
  - name: Install autoconf for building OpenSCAP
    apt:
      name: autoconf
  - name: Install automake for building OpenSCAP
    apt:
      name: automake
  - name: Install libtool for building OpenSCAP
    apt:
      name: libtool
  - name: Install pkg-config for building OpenSCAP
    apt:
      name: pkg-config
  - name: Install libcurl development files for building OpenSCAP
    apt:
      name: libcurl4-openssl-dev
  - name: Install libxml2 development files for building OpenSCAP
    apt:
      name: libxml2-dev
  - name: Install libxslt development files for building OpenSCAP
    apt:
      name: libxslt1-dev
  - name: Install libpcre development files for building OpenSCAP
    apt:
      name: libpcre3-dev
  - name: Install librpm development files for building OpenSCAP
    apt:
      name: librpm-dev
  - name: Install swig for building OpenSCAP
    apt:
      name: swig
  - name: Install libgcrypt development files for building OpenSCAP
    apt:
      name: libgcrypt20-dev
  - name: Install Python development files for building OpenSCAP
    apt:
      name: python-dev
  - name: Fetch the OpenSCAP source version {{ openscap_version }}
    get_url:
      url: https://github.com/OpenSCAP/openscap/releases/download/{{ openscap_version }}/openscap-{{ openscap_version }}.tar.gz
      dest: /tmp/openscap-src.tar.gz
  - name: Unpack the OpenSCAP source.
    unarchive:
      src: /tmp/openscap-src.tar.gz
      dest: /tmp
      creates: /tmp/openscap-{{ openscap_version }}/Makefile
  - name: Build OpenSCAP
    command: ./build_oscap.sh "/tmp/openscap-{{ openscap_version }}"
    args:
      creates: /tmp/openscap-installed/bin/oscap
  - name: Install cmake used during the SCAP security guide build 
    apt:
      name: cmake
  - name: Install libxml2 util needed to build the security guide
    apt:
      name: libxml2-utils
  - name: Install expat needed to build the security guide
    apt:
      name: expat
  - name: Install lxml package for python needed to build the security guide
    apt:
      name: python-lxml
  - name: Clone the SCAP security guide frim github
    git: 
      repo: https://github.com/OpenSCAP/scap-security-guide.git
      dest: /tmp/scap-security-guide
  - name: Build SCAP security guide
    script: ./build_oscap-sec-guide.sh "/tmp/scap-security-guide"

